---
- name: Execution time optimization
  hosts: webservers
  gather_facts: false
  become: true
  tasks:

    - name: Intalls required packages
      ansible.builtin.dnf:
        name:
          - httpd
          - httpd-tools
          - mod_ssl
          - php
          - php-mysqlnd
        state: latest

    - name: Ensures serices are started
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: Permit traffic for web server ports
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - http
        - https
