---
- name: Test default filter
  hosts: servera.lab.local
  gather_facts: false
  become: true
  tasks:
    - name: Uses default value for variable
      ansible.builtin.user:
        name: webadmin
        comment: "Web Master"
        groups: apache
        password: "{{ '123456' | password_hash('sha512') }}"
        update_password: on_create
        
