---
- name: Test template
  hosts: all
  become: true
  tasks:
    - name: Creates /etc/hosts files from the ansible inventory
      ansible.builtin.template:
        src: templates/hosts.j2
        dest: /etc/hosts
